### ISSUE TITLE
Application crash if profile step < 25m

### ISSUE THREAD

**Issue by sergebdt** [NTIA/ehata#5]
A fixed array of size 400 is allocated on the stack in PreprocessTerrainPath.cpp, routine 'ComputeTerrainStatistics'.
```
   float pfl_segment[400];
```
Where it holds up to 10km of path.
So if the step between profile points is below 25m, a buffer overrun will happen.

Possible simple solution are either:
 - do not allow step smaller than 25m, in the entry point of the model
 - or dynamically allocate the array. This is the approach taken by Winnforum
```
    float *pfl_segment = new float[i_end - i_start + 2];
   ...
    delete[] plf_segment;
```
See https://github.com/Wireless-Innovation-Forum/Spectrum-Access-System/blob/master/src/harness/reference_models/propagation/ehata/its/PreprocessTerrainPath.cpp#L176

Note that some other alternatives could be:
 - use of `std::vector pfl_segment(i_end - i_start+2);` : requires to use the C++ standard library, so the code is no more pure-C compatible
 - variable stack array, if your compiler supports it (moder ones do): `float pfl_segment[i_end-i_start + 2];`

There is the same issue in function 'MobileTerrainSlope()' with array:
```
float pfl_segment[400] = { 0 };
```
In Winnforum we did:
```
    float *pfl_segment = new float[int(10000/xi) + 4]();
   ...
    delete[] pfl_segment;
```
although the other option could be done as well

**Comment by wkozmaNTIA** [comment]
For clarification, this change was made, but the array size is one smaller than commented above, for the following reason:

In ComputeTerrainStatistics(),

```
  0   1   2   3   4   5   6   7
---------------------------------
|np |xi |   |   |   |   |   |   |
---------------------------------
```

Say you want to copy out elements 2 through 6, ie,
i_start = 2
i_end = 6

for total of 5 elements.  Thus,

double *pfl_segment = new double[i_end - i_start + 1];

since pfl_segement doesn't contain np and xi.

In MobileTerrainSlope(), you include np and xi, so its 'new double[i_end - i_start + 3]'

**Comment by sergebdt** [comment]
Yes you are right. We put a +2 instead of a +1 just to be safe, in case a consuming function had a buffer overrun of 1 (was the case of quantile function before it got fixed - see other ticket).
